WIP

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,15 +1,11 @@
 #!/usr/bin/env bash
-# -> => > >=
-# Symlinks
-# ln -s target linkname
-#
-# TODO: Update, then add all configuration files, Remove existing files
-#
-# $HOME/.config/nvim
-# $HOME/.config/neofetch/config.conf
-# $HOME/.config/raycast/config.json
 
-DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
+# Check for GNU Stow
+if ! command -v stow &> /dev/null
+then
+    echo "GNU Stow could not be found, please install it first."
+    exit
+fi
 
 mkdir -p $HOME/.config
 
@@ -38,9 +34,13 @@ stow --target=$HOME starship
 # echo COPYING .gitconfig
 rm -rf $HOME/.gitconfig
 rm -rf $HOME/.config/git
-mkdir -p $HOME/.config/git
 stow --target=$HOME git
 git config --global core.excludesFile $HOME/.config/git/.gitignore_global
+
+# Ghostty Terminal Emulator
+echo COPYING .config/ghostty/config
+rm -rf $HOME/.config/ghostty
+stow --target=$HOME ghostty
 
 ### To Stow
 
@@ -76,12 +76,6 @@ echo COPYING .config/alacritty/alacritty.toml
 rm -rf $HOME/.config/alacritty/
 mkdir -p $HOME/.config/alacritty
 ln -s $DOTFILES/alacritty/alacritty.toml $HOME/.config/alacritty/alacritt.toml
-
-# Ghostty Terminal Emulator
-echo COPYING .config/ghostty/config
-rm -rf $HOME/.config/ghostty/config
-mkdir -p $HOME/.config/ghostty
-ln -s $DOTFILES/ghostty/config $HOME/.config/ghostty/config
 
 # echo COPYING .config/raycast
 # rm -rf $HOME/.config/raycast
